version: '3.8'

services:
  vitepress:
    build: .
    ports:
      - "5173:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run docs:dev"

  # 生产环境服务 (取消注释使用)
  # vitepress-prod:
  #   build: .
  #   ports:
  #     - "80:80"
  #   restart: always