version: '3.8'

services:
  vitepress-release:
    build:
      context: .
      dockerfile: docker/release/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # 如果需要持久化构建结果可以取消下面注释
    # volumes:
    #   - vitepress-static:/usr/share/nginx/html

# volumes:
#   vitepress-static: